data:
  name: pix3d
  num_workers: 6
  batch_size: 18
  data_dir: ./data/pix3d
  mask_dir: mask_ocrnet0
  images_dir: img
  render_path: rendering_pix3d.pkl
  embedding_dir: rendering_pix3d.npy
  pix_size: 224
  view_num: 12
  training_json: pix3d_train.json
  test_json: pix3d_test.json
  # val_json: pix3d_val.json
  tau: 0.1
  # margin: 0.2

viz:
  log_freq: 50
  viz_freq: 100
  save_freq: 2000
  val_freq: 100

trainer:
  epochs: 500
  seed: 80132
  lr: 0.00005
  beta1: 0.5
  beta2: 0.999



models:
  pre_trained_path: './pre_trained/pix3d.pt'
  pre_train_resnet_root: './pretrained_resnet'
  save_root: './'
  z_dim: 128


setting:
  is_training: True
  is_aug: True # for data augmentation, flip, random crop...
  is_color: True # for data augmentation: color transfer
  is_from_scratch: True